# Intro to numpy - exercise solutions

This notebook contains model solutions to the exercises for this lesson.

Question 0) Installing + importing pandas and numpy
- Use ```! pip install```
- Use the standard two-letter aliases for each package

In [1]:
# solution here

! pip install pandas
! pip install numpy

import pandas as pd
import numpy as np

Question 1a) Define three parameters for creating a range of years:
- ```START_YEAR```: for the start of the period
- ```END_YEAR```: for the end of the period
- ```INTERVAL``` for the timegap between sequential years in the range

In [2]:
# example solution below

START_YEAR = 2030
END_YEAR = 2060
INTERVAL = 5

Question 1b) Generate a numpy array which contains the years defined by these three parameters
- Call the array variable ```years```
- Use the ```np.arange()``` method. You can look up the syntax for this online.
- Run ```print(years)``` to make sure this gives you what you expect. 

In [3]:
# solution below

years = np.arange(start=START_YEAR,
                  stop=END_YEAR+INTERVAL,
                  step=INTERVAL)

years

array([2030, 2035, 2040, 2045, 2050, 2055, 2060])

Question 1c) Generate another array of same length with some numerical data.
- Use ```len(years)``` to guarantee the array has same number of values
- Use ```np.random.randint()```
- Make the numbers generated be between 3e8 and 5e8
- Call this array ```emissions```

In [4]:
# solution below

baseline_emissions = np.random.randint(3e8, 4e8, len(years))

Question 2a) Store the value for the first element in the baseline_emissions array.
- Hint: remember indexing!
- Store this in a variable called ```starting_emissions```.

In [5]:
# solution below

starting_emissions = baseline_emissions[0]

Question 2b) Find the mean of the ```baseline_emissions``` values. 
- Store this in a variable called ```average_emissions```.

In [6]:
# solution below

average_emissions = baseline_emissions.mean()

Question 2c) Work out the difference between your ```average_emissions``` and ```starting_emissions``` variables.
- Store this as ```difference_to_average```.

In [7]:
# solution below

difference_to_average = starting_emissions - average_emissions

Question 2d) Generate a new array with only the values of ```emissions``` which are higher than ```average_emissions```.
- Call this array ```high_emissions```
- Hint: remember masking and indexing!

In [8]:
# solution below

# explicitly defining the mask first
mask = baseline_emissions > average_emissions
high_emissions = baseline_emissions[mask]

# or doing all of this in one step
high_emissions = baseline_emissions[baseline_emissions > average_emissions]

Question 3a) Convert the values in your ```baseline_emissions``` array and ```starting_emissions``` variable from MtCO2e -> kgCO2e.
- First define a numerical value for your ```conversion_factor```
- Then divide your ```emissions``` array by this value, making sure to store the result in the variable.

In [9]:
# solution below

conversion_factor = 1e6

baseline_emissions = baseline_emissions / conversion_factor
starting_emissions = starting_emissions / conversion_factor

Question 3b) Generate a new array which interpolates linearly between ```starting_emissions``` and **zero** across your defined time period.
- Call this array ```simple_nz_pathway```
- Hint: use ```np.linspace()```

In [10]:
# solution below

simple_nz_pathway = np.linspace(start=starting_emissions,
                                stop=0,
                                num=len(years))

simple_nz_pathway

array([329.012958, 274.177465, 219.341972, 164.506479, 109.670986,
        54.835493,   0.      ])

Question 3c) Generate a new array which interpolates linearly between ```starting_emissions``` and **-100** across your defined time period.
- Call this array ```simple_net_negative_pathway```
- Hint: use ```np.linspace()``` again, but change the ```stop``` argument.

In [11]:
# solution below

simple_net_negative_pathway = np.linspace(start=starting_emissions,
                                stop=-100,
                                num=len(years))

simple_net_negative_pathway

array([ 329.012958  ,  257.51079833,  186.00863867,  114.506479  ,
         43.00431933,  -28.49784033, -100.        ])

Question 4a) We have four equal length numpy arrays. Let's make them into a 2D array.
- Hint: use ```np.column_stack()```
- Call this ```emissions_data```

In [12]:
# solution below

emissions_data = np.column_stack([years,
                                  baseline_emissions,
                                  simple_nz_pathway,
                                  simple_net_negative_pathway])

emissions_data

array([[2030.        ,  329.012958  ,  329.012958  ,  329.012958  ],
       [2035.        ,  357.91225   ,  274.177465  ,  257.51079833],
       [2040.        ,  379.678181  ,  219.341972  ,  186.00863867],
       [2045.        ,  342.554453  ,  164.506479  ,  114.506479  ],
       [2050.        ,  322.640462  ,  109.670986  ,   43.00431933],
       [2055.        ,  380.969134  ,   54.835493  ,  -28.49784033],
       [2060.        ,  395.965097  ,    0.        , -100.        ]])

In [14]:
emissions_data.shape

(7, 4)

Question 4b) Pass this array into a pandas dataframe.
- Use ```pd.Dataframe()```
    * Make sure you specify both the ```data``` and ```columns``` arguments.
    * Use these column names: ["years", "baseline_emissions", "net_zero_pathway", "net_negative_pathway"]
- Store this as ```emissions_df```.

In [ ]:
# solution below

# define column names in a list for ease first
column_names = ["years",
                "baseline_emissions",
                "net_zero_pathway",
                "net_negative_pathway"]

emissions_df = pd.DataFrame(data=emissions_data, columns=column_names)

Question 4c) Set the ```years``` column as your index for ease.
- Hint: use the ```pd.DataFrame.set_index()``` method.
- Make sure you assign the result back to your ```emissions_df``` variable.

In [ ]:
# solution below

emissions_df = emissions_df.set_index("years")

Question 4c) Run the code below to see your emissions pathway!

In [ ]:
! pip install matplotlib

import sys
import os

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), "../../.."))
sys.path.append(PROJECT_ROOT)

In [ ]:

import matplotlib.pyplot as plt
from utils import theme

fig, axs = plt.subplots(figsize=(8,3), layout="constrained")

axs.plot(emissions_df["baseline_emissions"], color=theme.Colors["orange"])
axs.plot(emissions_df["net_zero_pathway"], color=theme.Colors["vibrant purple"])
axs.plot(emissions_df["net_negative_pathway"], color=theme.Colors["aubergine"])
axs.legend(emissions_df.columns, 
    loc="center left",
    bbox_to_anchor=(1.02, 0.5),
)
axs.set_ylabel("Emissions (MtCO$_2$e)")

theme.zero_line(axs, hide_bottom_spine=True)