# Intro to numpy

This notebook has been set up to cover some introductory concepts in numpy for CCC colleagues.

## What is numpy?

In a previous session, we covered the python `pandas` library. We expect that much of our modelling work will involve using pandas, as it is the most popular data library for manipulation of tabular data.

However, much of the core calculation and data manipulation logic in pandas is actually defined in another library - the `numpy` library. Numpy is sort of like pandas' engine, on top of which a load of functionality is added to simplify and enhance data manipulation.
Numpy (NUMerical PYthon) is a very powerful library for performing mathematical operations on ordered lists of numerical data, which are referred to as "arrays". The numpy `ndarray` is the core object which defines the properties and functionality associated with these data structures.

Let's take a whistlestop tour through some core numpy functionality.

## Why bother with numpy at all?

In many scenarios we do not in fact need to use numpy, as pandas provides an easier interface with our data, and provides functionality that we need. However, the additional functionality does slow things down, which means that in some cases we might prefer to use numpy. Some examples of best uses are set out below:

- `numpy` is better with:
    - clean, purely numerical data
    - vector and matrix data structures
    - maths-heavy operations like linear algebra or optimisation

- `pandas` is better with: 
    - messy, incomplete, and mixed type data
    - tabular data, which comes from sources like CSV, excel, SQL etc
    - finicky data cleaning and manipulation operations

Let's take a whistlestop tour through some core numpy functionality.

In [ ]:
# first, installing and importing the numpy library
# note that numpy is a core dependency of pandas, so you will already have this installed if
# you've installed pandas
# This DOES NOT mean that you don't have to IMPORT numpy separately if you want to access its functionality
# directly

!pip install numpy

import numpy as np

In [ ]:
# let's generate a numpy array and take a look at it
# TODO: add code below here

x = np.arange(1,101,1)
y = np.linspace(500, 40000, 100)

array([  500.        ,   898.98989899,  1297.97979798,  1696.96969697,
        2095.95959596,  2494.94949495,  2893.93939394,  3292.92929293,
        3691.91919192,  4090.90909091,  4489.8989899 ,  4888.88888889,
        5287.87878788,  5686.86868687,  6085.85858586,  6484.84848485,
        6883.83838384,  7282.82828283,  7681.81818182,  8080.80808081,
        8479.7979798 ,  8878.78787879,  9277.77777778,  9676.76767677,
       10075.75757576, 10474.74747475, 10873.73737374, 11272.72727273,
       11671.71717172, 12070.70707071, 12469.6969697 , 12868.68686869,
       13267.67676768, 13666.66666667, 14065.65656566, 14464.64646465,
       14863.63636364, 15262.62626263, 15661.61616162, 16060.60606061,
       16459.5959596 , 16858.58585859, 17257.57575758, 17656.56565657,
       18055.55555556, 18454.54545455, 18853.53535354, 19252.52525253,
       19651.51515152, 20050.50505051, 20449.49494949, 20848.48484848,
       21247.47474747, 21646.46464646, 22045.45454545, 22444.44444444,
      

A key thing to understand about numpy arrays of this shape is that they are vectors, mathematically, and behave as such.

In [15]:
# numpy arrays support vectorized operations
# this means that performing an operation on a numpy array
# automatically applies it to every single element in that array
# for example:

x * 2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
# when we perform an operation between two arrays
# we get the element wise operation

x / y

array([0.002     , 0.00222472, 0.00231128, 0.00235714, 0.00238554,
       0.00240486, 0.00241885, 0.00242945, 0.00243776, 0.00244444,
       0.00244994, 0.00245455, 0.00245845, 0.00246181, 0.00246473,
       0.00246729, 0.00246955, 0.00247157, 0.00247337, 0.002475  ,
       0.00247647, 0.00247782, 0.00247904, 0.00248017, 0.0024812 ,
       0.00248216, 0.00248305, 0.00248387, 0.00248464, 0.00248536,
       0.00248603, 0.00248666, 0.00248725, 0.0024878 , 0.00248833,
       0.00248883, 0.0024893 , 0.00248974, 0.00249016, 0.00249057,
       0.00249095, 0.00249131, 0.00249166, 0.00249199, 0.00249231,
       0.00249261, 0.0024929 , 0.00249318, 0.00249345, 0.0024937 ,
       0.00249395, 0.00249419, 0.00249441, 0.00249463, 0.00249485,
       0.00249505, 0.00249525, 0.00249544, 0.00249562, 0.0024958 ,
       0.00249597, 0.00249614, 0.0024963 , 0.00249645, 0.00249661,
       0.00249675, 0.00249689, 0.00249703, 0.00249717, 0.0024973 ,
       0.00249742, 0.00249755, 0.00249767, 0.00249778, 0.00249

In [29]:
# let's do some operations on said data
# 

print(np.mean(x))
print(np.max(y))
print(np.sum(x))

50.5
40000.0
5050


In [28]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316,
       -0.15862267, -0.91652155, -0.83177474,  0.01770193,  0.85090352,
        0.90178835,  0.12357312, -0.76825466, -0.95375265, -0.26237485,
        0.67022918,  0.98662759,  0.39592515, -0.55878905, -0.99975517,
       -0.521551  ,  0.43616476,  0.99287265,  0.63673801, -0.30481062,
       -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,  0.82682868,
       -0.02655115, -0.85551998, -0.89792768, -0.11478481,  0.77

In [36]:
# we can pack these together into a 2D array
# this is now a matrix


arr = np.array([x, y])

arr

array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
        5.00000000e+00, 6.00000000e+00, 7.00000000e+00, 8.00000000e+00,
        9.00000000e+00, 1.00000000e+01, 1.10000000e+01, 1.20000000e+01,
        1.30000000e+01, 1.40000000e+01, 1.50000000e+01, 1.60000000e+01,
        1.70000000e+01, 1.80000000e+01, 1.90000000e+01, 2.00000000e+01,
        2.10000000e+01, 2.20000000e+01, 2.30000000e+01, 2.40000000e+01,
        2.50000000e+01, 2.60000000e+01, 2.70000000e+01, 2.80000000e+01,
        2.90000000e+01, 3.00000000e+01, 3.10000000e+01, 3.20000000e+01,
        3.30000000e+01, 3.40000000e+01, 3.50000000e+01, 3.60000000e+01,
        3.70000000e+01, 3.80000000e+01, 3.90000000e+01, 4.00000000e+01,
        4.10000000e+01, 4.20000000e+01, 4.30000000e+01, 4.40000000e+01,
        4.50000000e+01, 4.60000000e+01, 4.70000000e+01, 4.80000000e+01,
        4.90000000e+01, 5.00000000e+01, 5.10000000e+01, 5.20000000e+01,
        5.30000000e+01, 5.40000000e+01, 5.50000000e+01, 5.600000

In [30]:
# show how it interacts with pandas

!pip install pandas

import pandas as pd

In [40]:
df = pd.DataFrame(
                {"x" : x,
                 "y" : y}
                 )

df

,x,y
0,1,500.000000
1,2,898.989899
2,3,1297.979798
3,4,1696.969697
4,5,2095.959596
...,...,...
95,96,38404.040404
96,97,38803.030303
97,98,39202.020202
98,99,39601.010101
