# 2 NumPy

## 2.1 But first, what is a package?

A package is a collection of Python _modules_, where a _module_ is a single
file containing Python code.

Packages, amongst other things, may define functions, variables, and classes.
Most packages you will use are hosted on [PyPI](https://pypi.org/) (pronounced
"pie pea eye").

`pip` is the preferred installer program for Python packages, and can be used
to install packages from PyPI. From the command line we install packages with:
`pip install packagename`.

To use packages we must _import_ them using the `import` keyword

## 2.2 Introduction to NumPy

[NumPy](https://numpy.org/about/) is at the _core_ of scientific computing in
Python.

Whether they know it or not, _almost every scientist_ working in Python
utilises the power of NumPy.

NumPy defines objects for storing large, multi-dimensional arrays and matrices,
and provides high-level mathematical functions to operate on these objects.

In doing so NumPy brings the computational performance of languages like
[C](https://en.wikipedia.org/wiki/C_(programming_language) and
[Fortran](https://en.wikipedia.org/wiki/Fortran) into the comfort of Python.

We can import NumPy using the `import` keyword:

In [ ]:
# Import the numpy package
import numpy

We use a `.` to access things from _within_ `numpy`

In [3]:
# Access the array function from numpy (more on this later)
numpy.array([1, 2, 3])  

array([1, 2, 3])

However, if we use a package a lot typing it's name over and over becomes
tedious.

We can give packages a short name by _aliasing_ them with the `as` keyword:

In [7]:
# Alias numpy to np
import numpy as np

# Access the array function with our shorthand
np.array([1, 2, 3])

array([1, 2, 3])

We can alias `numpy` to whatever shorthand we like.

However, by convention, users tend to alias `numpy` as `np`

## 2.3 NumPy arrays

NumPy's main object is the array.

NumPy's array object is _similar_ to Python's list object, but is much better
suited to data-oriented tasks.

We can construct NumPy arrays from lists:

In [8]:
# List of the numbers 1, 2, 3, 4 and 5
y_list = [1, 2, 3, 4, 5]

# Array of the numbers 1, 2, 3, 4 and 5
y_array = np.array(y_list)
y_array

array([1, 2, 3, 4, 5])

We can use the `type()` function to see that `y_array` really is a new data type:

In [9]:
type(y_array)

numpy.ndarray

### 2.3.1 Homogeneity

_All_ the entries of a NumPy array must be of _the same type_.

In this way we say that NumPy arrays are _homogeneous_.

Recall that lists can contain any mix of _different_ data types (they are
_heterogeneous_).

The array's `.dtype` _attribute_ tells us what type of data is stored within
our array:

In [11]:
y_array.dtype

dtype('int64')

### 2.3.2 Elementwise operations

With lists the `+` operator performed concatenation and the `*` operator
performed repetition.

However, when used on NumPy arrays these operators perform _elementwise_
arithmetic:

In [12]:
# Array of the numbers 1, 2 and 3
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [13]:
# Addition of arrays is performed elementwise
x + x

array([2, 4, 6])

In [14]:
# Multiplication of arrays is performed elementwise
x * x

array([1, 4, 9])

NumPy's mathematical functions operate on arrays elementwise:

In [15]:
# Exponentiate every entry in x
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [16]:
# Take the (natural) logarithm of every entry in x
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [17]:
# Take the sine of every entry in x
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

### 2.3.3 Broadcasting

Broadcasting refers to how NumPy performs operations on arrays and scalars and
arrays of different shapes.

Subject to certain constraints, the smaller array (or scalar) is “broadcast”
across the larger array so that their shapes are compatible to perform the
desired operation: 

In [18]:
# 100 is 'broadcast' across x to perform elementwise multiplication
x * 100

array([100, 200, 300])

In [19]:
# 100 is 'broadcast' across x to perform elementwise addition
x + 100

array([101, 102, 103])

## Quiz

Please complete **Quiz 2.1**.

Simply read each code snippet and indicate your answer.

### 2.3.4 2-d arrays, and beyond!

An array's `.ndim` attribute tells us how many _dimensions_ it has:

In [25]:
x.ndim

1

We can construct arrays with more than one dimension using lists of lists:

In [28]:
# Constructing a 4x2 array from a list of lists
x = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
x.ndim

2

The `.shape` attribute of an array reports the number of entries in each of its
dimensions.

For a two-dimensional array this tells us the number of rows and columns:

In [29]:
# (row, col)
x.shape

(4, 2)

### 2.3.5 Extracting elements from arrays

We can extract elements from arrays in much the same manner as we extracted
elements from lists

In [30]:
# Array of the numbers 1, 2, 3, 4 and 5
y = np.array([1, 2, 3, 4, 5])

# Extract the first element of y
y[0]

np.int64(1)

The slice operator `:` behaves as it did when indexing lists:

In [31]:
# Extract y[1], y[2] and y[3]
y[1:4]

array([2, 3, 4])

In [32]:
# Extract the first three entries of y
y[:3]

array([1, 2, 3])

With a two-dimensional array `x` we extract the entry in row `i`, column `j`
with `x[i, j]`:

In [ ]:
# Array with 4 rows and 2 columns
x = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

# Extract the element of x in row 0, column 1
x[0, 1]

In [ ]:
# Extract the element of x in row 2, column 0
x[2, 0]

We can use the slice operator `:` to extract entire rows and columns:

In [33]:
# Extract all the entries in column 1 of x
x[:, 1]

array([2, 4, 6, 8])

In [34]:
# Extract all the entries in row 2 of x (equivalent to x[2])
x[2, :]

array([5, 6])

Just as with lists, we can also use the slice operator to extract ranges of
values:

In [35]:
# Extract entries in column 1 for rows 1, 2, and 3
x[1:4, 1]

array([4, 6, 8])

## Exercises

Please complete the [exercises contained here](2-exercises.ipynb)

[Next Chapter >>>](../chapter3/3-demo.ipynb)
